Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 112
    Strategy: Resource
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'tiny_ae_fixed_point_v1/keras_model.h5'
OutputDir: tiny_ae_fixed_point_v1
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: bCaA4Fe8
Version: 1.0.0
