Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    ClockPeriod: 10
    Precision: ap_fixed<16,6>
    ReuseFactor: 16
    Strategy: Resource
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'mini_ae_resource_safe/keras_model.h5'
OutputDir: mini_ae_resource_safe
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: C8b445F9
Version: 1.0.0
